[project]
name = "avo-xtb"
version = "0.3.1"
requires-python = ">= 3.10"
authors = [
    {name = "Matthew J. Milner", email = "matterhorn103@proton.me"},
    ]
maintainers = [
    {name = "Matthew J. Milner", email = "matterhorn103@proton.me"},
    ]
description = "Access the full power of xtb through the Avogadro interface."
readme = "README.md"
license = {text = "BSD 3-Clause License"}


[project.optional-dependencies]
linter-formatter = ["ruff"]

[project.urls]
Repository = "https://github.com/matterhorn103/avo_xtb"

[tool.ruff]
target-version = "py310"

[tool.avogadro]
type = "commands"
commands = [
    {name = "configure", command = "config.py"},
    {name = "energy", command = "energy.py"},
    {name = "optimize", command = "opt.py"},
    {name = "frequencies", command = "freq.py"},
    {name = "opt-freq", command = "ohess.py"},
    {name = "orbitals", command = "orbitals.py"},
    {name = "conformers", command = "conformers.py"},
    {name = "md", command = "md.py"},
    {name = "run", command = "run.py"},
    {name = "open", command = "open.py"},
    {name = "install", command = "install.py"},
    {name = "go-to-docs", command = "docs.py"},
    ]
