[project]
name = "avo_xtb"
version = "0.5.0"
description = "A convenient interface to xtb (and CREST) in Avogadro 2"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
